### ISSUE TITLE
Bug - Command Prompt without description for selected commands

### ISSUE THREAD

**Issue by dejunnn** [AY1920S2-CS2113-T15-4/tp#25]
Currently, our parser is unable to handle a command prompt with no description when a description is expected.

For eg. entering set-name with no arguments after will cause the program to fail as the code expects an argument after the command prompt.

Should be an easy fix related to Parser, will assign myself to fix this bug. Progress can still continue as this is a minor issue.

**Comment by DDzuikeai** [comment]
Have fixed this bug.
